# Generated by Django 4.2.2 on 2023-07-30 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('actions', '0004_follower'),
        ('main', '0004_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(
                blank=True, null=True, related_name='followers', through='actions.Follower', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
