# Generated by Django 4.2.2 on 2023-08-05 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('actions', '0008_eventaction'),
        ('main', '0005_remove_user_followers_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(
                blank=True, related_name='followers', through='actions.Follower', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
