# Generated by Django 4.2.2 on 2023-11-13 13:53

from django.db import migrations, models
import main.services


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_alter_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(
                blank=True, default='no_ava/no_ava.jpg', upload_to=main.services.user_directory_path
            ),
        ),
    ]
