# Generated by Django 4.2.7 on 2023-11-14 18:14

from django.db import migrations, models
import main.services


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='no_ava.png', upload_to=main.services.user_directory_path),
        ),
    ]
