# Generated by Django 4.2.2 on 2023-07-24 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0002_likedislike_created_alter_likedislike_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='likes_dislikes',
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
    ]
