# Generated by Django 4.2.2 on 2023-07-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('actions', '0004_follower'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.UniqueConstraint(
                fields=('subsciber', 'to_user'), name='follower_subsciber_to_user_unique'
            ),
        ),
    ]
