# Generated by Django 4.2.2 on 2023-08-01 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0007_remove_follower_follower_subsciber_to_user_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('update_avatar', 'Update avatar')], max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
